### ISSUE TITLE
Bidireccional sync wl.pull and gh.push

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/runbot-addons#124]
We need check a `git diff wl..gh` in order to detect differences between weblate and github in order to create a new runbot build

Currently just detect if there are changes from weblate but weblate is not updated if there are changes from github

**Comment by JesusZapata** [comment]
@moylop260 
This issue was fixed with https://github.com/Vauxoo/runbot-addons/pull/126 PR 
Could do you close?
