### ISSUE TITLE
[9.0] runbot_travis2docker: error installing

### ISSUE THREAD

**Issue by ygol** [Vauxoo/runbot-addons#131]
I would like to install the runbot addons "runbot_travis2docker" in odoo 9 but getting the following error:

`
[...]
File "/home/runbot/instance/runbot-addons/runbot_travis2docker/models/runbot_build.py", line 14, in <module>
    from travis2docker.travis2docker import main as t2d
ImportError: cannot import name main`

How would I investigate the problem?
TIA

**Comment by moylop260** [comment]
did you have installed travis2docker python package?

**Comment by moylop260** [comment]
The line reported is not the current lines used
https://github.com/Vauxoo/runbot-addons/blob/9.0/runbot_travis2docker/models/runbot_build.py#L14

you should update the last sha of this repository

**Comment by ygol** [comment]
Indeed, I had a problem with the cloned repos. 
I followed the instructions from: 
` https://github.com/Vauxoo/runbot`
but there is no branch 9 and ended with the wrong branch.
Your gist helped:
`https://gist.github.com/moylop260/c1d2fe1ccc9c009e6d8d`

tnx again.
