### ISSUE TITLE
library cfdilib not found

### ISSUE THREAD

**Issue by luistorresm** [Vauxoo/runbot-addons#137]
After of the update I have the following error in runbot to https://github.com/vauxoo/odoo-mexico-v2/

`except_orm: ('Error', u'Unable to install module "l10n_mx_facturae_base" because an external dependency is not met: No module named cfdilib')`

This library is found in the[ requeriments.txt](https://github.com/Vauxoo/odoo-mexico-v2/blob/8.0/requirements.txt#L10)

http://runbot.vauxoo.com/runbot/static/build/39583-8-0-940c07/logs/job_20_test_all.txt

**Comment by luistorresm** [comment]
FYI @moylop260 @JesusZapata

**Comment by moylop260** [comment]
After finish the build will be fixed:
https://hub.docker.com/r/vauxoo/odoo-80-image-shippable-auto/builds/bjtdbmsvlvs3x234xc7nlac/

**Comment by osvalr** [comment]
Hi @moylop260, I see that runbot for 10.0 (logs in http://runbot.vauxoo.com/runbot/static/build/39673-10-0-ae257e/logs/job_20_test_all.txt) is still getting the same error (rebuilt twice), and also I see in https://hub.docker.com/r/vauxoo/odoo-80-image-shippable-auto/builds/ is getting build errors and canceled...

**Comment by hugho-ad** [comment]
@osvalr may be because the docker images is still building 
![image](https://user-images.githubusercontent.com/10233975/29288455-6d47dfd0-80fe-11e7-9d5b-795612b4d030.png)

**Comment by osvalr** [comment]
@hugho-ad you were right, the image build just finished and it ran with success
