### ISSUE TITLE
No module named signxml

### ISSUE THREAD

**Issue by osvalr** [Vauxoo/runbot-addons#138]
After of the update I have the following error in runbot to https://github.com/vauxoo/odoo-peru/

```bash
UserError: (u'Unable to install module "l10n_pe_edi" because an external dependency is not met: No module named signxml', None)
```

That package can be found on [requirements.txt](https://github.com/Vauxoo/odoo-peru/blob/10.0/requirements.txt#L4)

Any other info can be found at http://runbot.vauxoo.com/runbot/static/build/39591-10-0-f40624/logs/job_20_test_all.txt

**Comment by moylop260** [comment]
Duplicated with https://github.com/Vauxoo/runbot-addons/issues/137
