### ISSUE TITLE
Runbot is returning a false red to the Gitlab CI

### ISSUE THREAD

**Issue by tomeyro** [Vauxoo/runbot-addons#143]
**Current behaviour:**

Runbot builds are returning red to gitlab CI when there are warnings in the build log.

Runbot build: http://runbot.vauxoo.com/runbot/build/42796
Gitlab pipeline: https://git.vauxoo.com/vauxoo-dev/qualifirst/pipelines/7983

![image](https://user-images.githubusercontent.com/8657959/31451502-e5558f36-ae71-11e7-897a-08f47403f1c8.png)

**Expected behaviour:**

Runbot should return green even if warnings are found. Warnings are not fatal and they don't really break the build.

**Lines of interest:**

https://github.com/Vauxoo/runbot-addons/blob/9.0/runbot_gitlab_minimal/models/runbot_build.py#L54

---

CC: @JesusZapata @moylop260

**Comment by JesusZapata** [comment]
@tomeyro 
You can closed this issue ?
The PR with the solution was closed without merge
