### ISSUE TITLE
[9.0] runbot: Log en vivo

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/runbot-addons#15]
Los logs en vez de verse como texto plano, deben de ser capaz de verse como una shell embebida.
Widgetcito javascript.

En el header la librería declarada y el log_visor.html va a llamar el archivo.txt
runbot_url/log_visor.html?path_file=archivo.txt
(Se puede hacer un controller)

**Comment by moylop260** [comment]
@nhomar 
What is the driver?

**Comment by moylop260** [comment]
@nhomar 
What driver we will use it?

**Comment by moylop260** [comment]
@oscarolar 
Do you know the driver to use?

**Comment by oscarolar** [comment]
Log.io its cool but its harder to integrate
https://github.com/NarrativeScience/Log.io
If you want a simpler implementation with less features JQuery Log:
http://www.binpress.com/app/jquery-log-viewer/570
Log viewer is not that good, I will keep on looking for more tools.

**Comment by oscarolar** [comment]
Check this small Ajax method:
http://stackoverflow.com/questions/13623784/read-txt-file-real-time-with-javascript

**Comment by JesusZapata** [comment]
@moylop260 
Could do you assign this task to me?
This feature is necessary, for avoid many F5
