### ISSUE TITLE
[9.0] runbot_travis2docker:  I will like a button in the website interface for to kill the build

### ISSUE THREAD

**Issue by yaniaular** [Vauxoo/runbot-addons#21]
module: runbot_travis2docker
version: 9.0

**Expected behavior**
- I see my build and click here and kill build. ![Click and kill](https://cloud.githubusercontent.com/assets/7602170/10234223/f92e2872-685c-11e5-8ecc-d79f86a72711.jpeg)
  )

**Comment by deivislaya** [comment]
This is a good option to reduce the processing load on the servidor

**Comment by moylop260** [comment]
This is a good improvement that we had a time ago.
But the maintainers of project removed this feature.

They had suicide fails.
e.g. kill(build_1) <- result ups! runbot instance is down.

After a contributor created the fix https://github.com/odoo/odoo-extra/pull/38 and other one https://github.com/odoo/odoo-extra/pull/65

But we don't had merged this one without a reason.

We are waiting if the main maintainers saw something wrong.

We don't want create many changes in custom project to avoid diverge or create new errors in this sensible project.
