### ISSUE TITLE
[9.0] runbot_travis2docker: Error en depends

### ISSUE THREAD

**Issue by JulioSerna** [Vauxoo/runbot-addons#23]
version: 9.0

**Steps to reproduce**
- Rebuild in lodigroup

**Current behavior**
- Test fail [log](http://runbot2.vauxoo.com/runbot/static/build/00410-8-0-072962/logs/job_20_test_all.txt)

**Expected behavior**
Finish build

**Comment by JulioSerna** [comment]
@moylop260 

This happened when try to rebuild in Lodigroup or new PR
![runbot2 vauxoo com runbot static build 00410 8 0 072962 logs job_20_test_all txt](https://cloud.githubusercontent.com/assets/7595505/10253560/b10d447c-6903-11e5-8298-22a42b83db77.png)

**Comment by hugho-ad** [comment]
@JulioSerna este problema es ocasionado por los addons-vauxoo, estoy intentando localizar un commit donde no marque ese error, deduje que son los add-vx por que haciendo checkout a una.rama que tengo sin pull de lo más reciente , no me marca ese error

**Comment by JulioSerna** [comment]
@hugho-ad 

este es el que marca eso,
https://github.com/Vauxoo/addons-vauxoo/blob/8.0/website_customer_also_purchased/__openerp__.py#L8:L9

**Comment by JulioSerna** [comment]
Close because is not issue runbot

**Comment by hugho-ad** [comment]
@JulioSerna Lograste superar el error ?
