### ISSUE TITLE
[9.0] runbot_travis2docker: I can't display Vauxoo/rma builds

### ISSUE THREAD

**Issue by yaniaular** [Vauxoo/runbot-addons#24]
module: runbot_travis2docker
version: 9.0

**Steps to reproduce**
- Entrar en http://runbot2.vauxoo.com/runbot/repo/git-github-com-vauxoo-rma-git-18 

**Current behavior**
- 500: Internal Server Error
- [Error](http://awesomescreenshot.com/0a75awfza7)

**Expected behavior**
- Ver los builds de Vauxoo/rma :sob:

**Comment by yaniaular** [comment]
@moylop260 I can't display Vauxoo/rma builds :crying_cat_face:

**Comment by yaniaular** [comment]
@moylop260 With login display next: [Error](http://awesomescreenshot.com/08c5awhc72)

**Comment by moylop260** [comment]
Thank for issue

This problem is a issue from base modules.
If you have a sticky branch without builds then make a error

**Comment by moylop260** [comment]
FYI You can fix it directly in database removing sticky value in runbot.branch
