### ISSUE TITLE
[9.0] runbot_travis2docker: Error en rebuild

### ISSUE THREAD

**Issue by JulioSerna** [Vauxoo/runbot-addons#25]
module: runbot_travis2docker
version: 9.0

**Steps to reproduce**
- Crear Rebuild
  ![runbot repo localhost](https://cloud.githubusercontent.com/assets/7595505/10493324/138e1e8e-7276-11e5-8143-33ba6199fd86.png)

**Current behavior**
![400 bad request](https://cloud.githubusercontent.com/assets/7595505/10493330/1e64c1f0-7276-11e5-8127-984b6b4e6f3f.png)

**Expected behavior**
Crear rebuild

**Comment by moylop260** [comment]
@JulioSerna 
Thank for issue
Now is fixed in production with next PR: https://github.com/odoo/odoo-extra/pull/84
