### ISSUE TITLE
[9.0] runbot_travis2docker: error with build duplicate

### ISSUE THREAD

**Issue by Angelfentanez** [Vauxoo/runbot-addons#27]
When I try to duplicate a build I'm getting redirected to edit the original one instead of the duplicate.

![image](https://cloud.githubusercontent.com/assets/12100691/10559737/5231b7e2-74bd-11e5-9de6-7f6d27462744.png)

![image](https://cloud.githubusercontent.com/assets/12100691/10559685/9782e7a4-74bc-11e5-8a6e-12b7757e9c0b.png)

![image](https://cloud.githubusercontent.com/assets/12100691/10559689/ae538c7c-74bc-11e5-81a1-d0cfdce131ac.png)

![image](https://cloud.githubusercontent.com/assets/12100691/10559747/70ddb31c-74bd-11e5-94b4-14d19ec45b18.png)

**Comment by moylop260** [comment]
Reporta este issue en odoo/odoo y procura replicarlo con el runbot.odoo.com de ellos en la version 9.0 con la vista de partners

**Comment by moylop260** [comment]
Este issue es de odoo/odoo

**Comment by moylop260** [comment]
Este issue es de odoo/odoo
