### ISSUE TITLE
Better wording for message sent when build is being tested

### ISSUE THREAD

**Issue by hbto** [Vauxoo/runbot-addons#52]
![image](https://www.evernote.com/l/APA_wTy3Y2NGlKP-jsywVKOH5oxNy-d_uFIB/image.png)

**Comment by hbto** [comment]
At this stage when runbot is testing the build. It does not make sense to provide information on how to functionally debug the build as instance is not yet fully built thus inaccessible,

**Comment by luiseevaquer** [comment]
@hbto 
can you close this issue, please?

**Comment by nhomar** [comment]
in orcer to automatically close related issues you can set in your commit message the text:

closes #NUMBERISSUE
