### ISSUE TITLE
Duplicated emails the a build without changes

### ISSUE THREAD

**Issue by luistorresm** [Vauxoo/runbot-addons#54]
I have a PR in lodigroup repo (Vauxoo/lodigroup#441), and the last build that I generate of this PR was 18h time 30m ago, and today I received 6 emails for this build:

![resultados de busqueda luis_t vauxoo com correo de vauxoo sa de cv](https://cloud.githubusercontent.com/assets/7606656/13614206/fe0829b0-e534-11e5-8d4f-23b8a7829294.png)

In runbot, in the build register I get the next:
![error de envio de correos en runbot](https://cloud.githubusercontent.com/assets/7606656/13614226/1853aca4-e535-11e5-9f21-a74eb80756c6.png)

Is this correct?

**Comment by moylop260** [comment]
This error was by a large queue...
If you see this error again feel free of re-open it
