### ISSUE TITLE
Email address on email received is "admin@example.com"

### ISSUE THREAD

**Issue by luistorresm** [Vauxoo/runbot-addons#55]
The email address in email received from runbot, to notificate the state the of a build is admin@example.com

![-runbot testing 07370 441 bd120e pr 441 git github com vauxoo lodigroup luis_t vauxoo com correo de vauxoo sa de cv](https://cloud.githubusercontent.com/assets/7606656/13614462/3f8f248c-e536-11e5-873c-8e2c80d2476b.png)

Is this ok?

**Comment by moylop260** [comment]
Fixed

**Comment by luiseevaquer** [comment]
Fixed, email changed by @nhomar 

![email_changed](https://cloud.githubusercontent.com/assets/16093067/13618053/297fa3c4-e554-11e5-9a35-13addd6e7038.png)
