### ISSUE TITLE
Bad url in mail received

### ISSUE THREAD

**Issue by osvalr** [Vauxoo/runbot-addons#57]
This feature is great to be noticed when runbot is running and testing and mail me the result of it, so when I try to reach the related repository (or the pull request) using the hyperlinks in the mail it seems to be wrong.

Please, see the following demo video showing what I'm try to report

[![](http://img.youtube.com/vi/ACBuhEhtR34/0.jpg)](http://www.youtube.com/watch?v=ACBuhEhtR34")

**Comment by moylop260** [comment]
Fixed here: https://github.com/Vauxoo/runbot-addons/pull/56
Could you check again?

**Comment by osvalr** [comment]
Sure, I'll confirm when I get noticed

**Comment by osvalr** [comment]
confirming that this issue is fixed
