### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by osvalr** [Vauxoo/runbot-addons#59]
![image](https://cloud.githubusercontent.com/assets/2961943/13651439/94715842-e619-11e5-880b-fcd442197923.png)

---

Current: You must wait until runbot status **`chamges`**. 

Proposal: You must wait until runbot status **`changes`**. 

---

Current:  Thanks for your **`patient`**.
Proposal: Thanks for your **`patience`**. 
- **`NOTE`**: Please see this [Reference](http://www.gingersoftware.com/english-online/spelling-book/confusing-words/patience-patients)

---

Current:  You can have access to the logs of this build on plain text Here and Here or **`to the log of the running instance Here`**.

Proposal: You can have access to the logs of this build on plain text Here and Here or **`instance's logs Here`**.

**Comment by moylop260** [comment]
Fixed here https://github.com/Vauxoo/runbot-addons/pull/60
