### ISSUE TITLE
[IMP] use the same email title to make then colapse into a same mail  thread 

### ISSUE THREAD

**Issue by zaoral** [Vauxoo/runbot-addons#61]
Here is an example of my inbox. I have 3 mail threads for the same `PR # 774`

I will like that they shown at the same mail thread. I suppose this could be accomplish by using the same mail title.

Currently the [Fixed, Broken, Testing] prefix in the mail title could be the reason why the are not gather together.

I want that the email build update for the same PR belongs to the same thread.
NOTE: The body of the email will show the status of the build, the build id and the sha.

![image](https://cloud.githubusercontent.com/assets/7593953/13658755/402f86f4-e64c-11e5-9343-5a8c0ce9e274.png)

**Comment by moylop260** [comment]
IMHO A thread by PR is a good idea.
With stable branches we can use the sha to split them and avoid a infinite thread of stable branches.

The main problem with pr cases is that we will need to open the full email... Or we can add the result in top position of the body to fast view of the build result.

@Vauxoo/vauxoo-read 
What do you think about this issue?

**Comment by zaoral** [comment]
+1 to add the result information in top position of the body to fast view

I propose that the title of the message be lie this one

`[runbot-build] Organization/repo#PRNUM`

and left enough space to show the first info about the message with
something like this

`Build status` build id, sha number.

On Wed, Mar 9, 2016 at 11:55 PM, moylop260 notifications@github.com wrote:

> IMHO A thread by PR is a good idea.
> With stable branches we can use the sha to split them and avoid a infinite
> thread of stable branches.
> 
> The main problem with pr cases is that we will need to open the full
> email... Or we can add the result in top position of the body to fast view.
> 
> @Vauxoo/vauxoo-read https://github.com/orgs/Vauxoo/teams/vauxoo-read
> What do you think about this issue?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Vauxoo/runbot-addons/issues/61#issuecomment-194657359
> .

## 

_Lic. Katherine Zaoral_
_Vauxoo C.A. - Open Source Specialist_
github: zaoral
launchpad: kathy-zaoral

**Comment by zaoral** [comment]
The result will be show in our mail inbox something like this:

```
Vauxoo Runbot (4)     [runbot-build] Vauxoo/instance#450 - Fixed @ 7893 SHA h3f629405jf
```

**Comment by osvalr** [comment]
I agree to have a email thread by pull request builds updates

**Comment by yaniaular** [comment]
+1 i agree with the thread that @zaoral proposes

**Comment by moylop260** [comment]
@lescobarvx 
- For PR and stable branches change:
  - Body:
    
    `{build.result} @ {build.name} - build_{build.sequence} - {build.commit_message}.... (Current body)`
    e.g.
    `Fixed @ h3f629405jf - build_7893 - [REF] module: Change X ... (Current body)`
- For PR change:
  - Subject:
    `[runbot] {OWNER}/{PROJECT}#{BRANCH}`
    
    e.g.
    `[runbot] Vauxoo/instance#450`
- For stable branch:
  - Subject:
    `[runbot] {OWNER}/{PROJECT}#{BRANCH} - {build.name}`
    
    e.g.
    `[runbot] Vauxoo/instance#8.0 - h3f629405jf`

@Vauxoo/vauxoo-read @nhomar @hbto 
Are you agree?

**Comment by hbto** [comment]
+1 @moylop260 I agree

**Comment by JulioSerna** [comment]
I don't know if this is out of context, but a long time ago I wanted to do this in the mails of vauxoo
![recibidos 2 julio vauxoo com correo de vauxoo sa de cv](https://cloud.githubusercontent.com/assets/7595505/13894832/ed76fd4c-ed31-11e5-8ce6-cc660c7847dc.png)

Add that button like Github, I can see that is possible with this
 `</div>
<meta itemprop="description" content="View this Pull Request on GitHub"></meta>
</div>` 

But I never tried it,

@moylop260 @lescobarvx 

do you think this is possible to this mails of runbot?

**Comment by moylop260** [comment]
@JulioSerna 
We are working in this improvement in follow issue: https://github.com/Vauxoo/runbot-addons/issues/68

**Comment by zaoral** [comment]
Hi @lescobarvx @moylop260 

I found a strange behavior in the way that the build emails group in my inbox.
I let you here a [video](https://youtu.be/FPgNrSLiTNw), please review it and let me know what do you think is happening,

Best Regards.

**Comment by luiseevaquer** [comment]
@zaoral @moylop260 
It's strange, but it may be that are different commit and so not grouped in the same thread.
Do you have other cases with that behavior?

**Comment by luiseevaquer** [comment]
@zaoral 
Please, send me a copy of both email of PR#949 to check something

**Comment by zaoral** [comment]
@lescobarvx  I just sent the two emails copy.

I have something similar with PR 913 but is really odd and also send you the copy of the email. In this case I have different commits and different days and the behavior is different: the build email that are from different commit and different date are grouped. but In some moment they split into two threads I do not now why.

Also, there is something I want to ask you and @moylop260. See the PR 913 is really strange because It was merged and then like 4 mores builds were created. Obviously that is another issue very different for what we are talking about: Why this last 4 extra builds were created if I do not request for the build (I did not click on rebuild button or duplicate button). This builds I do now now why there were created. 

Getting back to the current issue, the split of the thread I leave here a visual copy to show you the email date and commit number for PR 913
- Email 1
  ![image](https://cloud.githubusercontent.com/assets/7593953/14183506/7654b0de-f73a-11e5-85b3-6cfb9b28276d.png)
- Email 2 
  ![image](https://cloud.githubusercontent.com/assets/7593953/14183514/7e433e0a-f73a-11e5-9a05-fcd96fc4a51d.png)

**Comment by luiseevaquer** [comment]
@zaoral 
Sorry, send me the plain text that shows you when you select the menu email "Mostrar original".
Please, I need the both mail of PR#949 to see the differences.

Menu:
![mostrar_original](https://cloud.githubusercontent.com/assets/16093067/14184910/4c6b01fe-f741-11e5-91be-daea455b5869.png)

Text Plain:
![texto_plano](https://cloud.githubusercontent.com/assets/16093067/14185129/46e6ccc6-f742-11e5-8a5b-907000d1654d.png)
