### ISSUE TITLE
[8.0] Can't Start Container, port is already allocated

### ISSUE THREAD

**Issue by hugho-ad** [Vauxoo/runbot-addons#62]
I rebuild 3 times, and each time I face the next error:

`Error response from daemon: Cannot start container 56bdc702734f373f5ad76a0458b43f51aaf2b57b37f0f37377399938bbc3bf72: failed to create endpoint build_7728 on network bridge: Bind for 0.0.0.0:3010 failed: port is already allocated`

![image](https://cloud.githubusercontent.com/assets/10233975/13677402/798da116-e6af-11e5-8a01-43eeb30e5864.png)

**Comment by moylop260** [comment]
Could you try again?

**Comment by hugho-ad** [comment]
Sure
![image](https://cloud.githubusercontent.com/assets/10233975/13678156/e4cc15a4-e6b2-11e5-93bf-fe69962e8c81.png)

I rebuild again.

**Comment by oscarolar** [comment]
Lo mismo aquí +1

On Thu, Mar 10, 2016 at 11:26 AM, Hugo Adan [Vauxoo] <
notifications@github.com> wrote:

> Sure
> [image: image]
> https://cloud.githubusercontent.com/assets/10233975/13678156/e4cc15a4-e6b2-11e5-93bf-fe69962e8c81.png
> 
> I rebuild again.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Vauxoo/runbot-addons/issues/62#issuecomment-194966602
> .

## 

Ing. Oscar Alcalá Rivera
_312-107-1704_ · oszckar@gmail.com ozckar@gmail.com

Vauxoo SA
Tlf: _+52 (477) 773.33.46_

_Open Source Enthusiast_

_LinuxCounter:__566085_
   [image: twitter] http://twitter.com/oscarolar [image: linkedIn]
http://www.linkedin.com/pub/oscar-alcal%C3%A1/3b/a79/922   [image:
Google+] http://plus.google.com/107659954580035981067/posts

[image: eco] No me imprimas si no es necesario. Protejamos el medio ambiente

**Comment by moylop260** [comment]
Fixed
Could you check again?
I saw the build with a valid state...
