### ISSUE TITLE
Use of cache to test just changed modules

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/runbot-addons#67]
Currently, a runbot build with many modules of a customer spent more than 1 hour to finish.

Now, with the current docker integration we can use a image cache based on stable branch and the pull request re-use this one (including databases, repositories...) to run the tests just in changed modules with `-u` param.

IMHO this improvement could reduce 80% of the time spent.

The plan:
![runbot - just modules changed](https://cloud.githubusercontent.com/assets/6644187/13797200/67b5dbb8-ead1-11e5-809d-ccb90391bcac.png)

**Comment by moylop260** [comment]
Thanks to @nhomar now I understand that use 
`--test-enable -u module_installed`
Could fail, because other module installed could change the demo data or python logic and broken the tests...

I need think in a better solution to re-use databases and don't broken the tests of modules installed or change a global tests by a particular tests.

**Comment by osvalr** [comment]
@moylop260 what about using the stable `openerp_template` database from runbot instead?

**Comment by zaoral** [comment]
I think maybe a 3 database approach could be useful.
- `openerp_template`: is the same database (base modules) run without unit test.
- `openerp_base`: (find a more suitable name) install yoytec complete but without unit test duplicating the openerp_template base.
- `openerp_test`: now will be a duplicate database from openerp_base were we run -u [list of modules with changes] --test-enable.

Run the unit test after module installation I think conceptually should work.

**Comment by zaoral** [comment]
This week I been making tests for improve my way to re use containers for development purpose with no success yet.

I found this [link](http://stackoverflow.com/questions/26734402/how-to-upgrade-docker-container-after-its-image-changed) that give me an idea: If we have a container A that have already created openerp_template database and tested openerp_test with complete all customer module app. Then container B will be a updated version of the first one that only run openerp_test -u updated_modules --test-enable. However this option I think is too risky

**Comment by yaniaular** [comment]
**yoytec_app_depends** = https://github.com/Vauxoo/yoytec/blob/8.0/yoytec/__openerp__.py#L33-L113
**real_yoytec_modules** = https://github.com/Vauxoo/yoytec/

Currently, when the openep_test BD is duplicated from openerp_template bd, it will proceed to install 62 modules (all modules in **yoytec_app_depends**). I think that can be reduced to 29 modules if we have previously installed the modules are not in yoytec repo (**real_yoytec_modules**).

Something like a **openerp_template_2 BD**

``` python
>>> yoytec_app_depends
['analytic', 'base_vat', 'l10n_pa', 'l10n_pa_vat', 'l10n_pa_cities', 'base_location', 'vat_partitioned', 'account_voucher', 'account_anglo_saxon', 'account_asset', 'import
_tax_tariff', 'invoice_allow_print', 'yoytec_ruc_validations', 'costing_method_settings', 'fiscal_printer', 'yoytec_sale_reports', 'sale_team_warehouse', 'yoytec_picking_w
ait_sale', 'sale_cash_register', 'purchase_requisition', 'purchase_requisition_for_everybody', 'purchase_double_validation', 'product_lifecycle', 'purchase_incoming_qty',
'product_properties_by_category', 'stock_location_code', 'procurement_jit', 'stock_picking_wave', 'product_unique_serial', 'product_manufacturer', 'product_unique_default_
code', 'yoytec_picking_report', 'warehouse_interim_receipt', 'yoytec_delivery_domicile', 'stock_forecast', 'mrp', 'yoytec_mrp', 'hr_blood_type', 'hr_employee_accessories',
 'hr_employee_declares_isr', 'hr_employee_dependant', 'hr_employee_licence', 'hr_employee_perception', 'hr_family', 'hr_passport_employee', 'hr_working_shifts_switch', 'hr
_lastname', 'hr_loan', 'l10n_pa_hr_marital_status', 'website_yoytec', 'admin_technical_features', 'auth_password_settings', 'instance_introspection', 'uom_security', 'yoyt
ec_crm_claim_partner_foreign', 'yoytec_rma_workflow', 'crm_claim_summary_report', 'partner_long_name', 'stock_transfer_avoid_lot_repeated_split', 'mail_notification_collec
tion', 'web_tree_image', 'yoytec_migration_fields']

>>> real_yoytec_modules
['deployment_files', 'invoice_allow_print', 'mail_notification_collection', 'oca_dependencies.txt', 'partner_long_name', 'README.md', 'sale_cash_register', 'theme_yoytec',
 'warehouse_interim_receipt', 'website_yoytec', 'yoytec', 'yoytec_account_collect', 'yoytec_checkout', 'yoytec_crm_claim_partner_foreign', 'yoytec_customer_rma_workflow',
'yoytec_delivery', 'yoytec_delivery_domicile', 'yoytec_migration_fields', 'yoytec_mrp', 'yoytec_picking_invoice_validation', 'yoytec_picking_report', 'yoytec_picking_wait_
sale', 'yoytec_rma_workflow', 'yoytec_ruc_validations', 'yoytec_sale_reports', 'yoytec_sale_workflow', 'yoytec_supplier_rma_report', 'yoytec_supplier_rma_workflow', 'yoyte
c_tools']

>>> set(yoytec_app_depends) - set(real_yoytec_modules)
set(['stock_picking_wave', 'admin_technical_features', 'import_tax_tariff', 'hr_employee_licence', 'web_tree_image', 'stock_location_code', 'account_voucher', 'hr_employee
_declares_isr', 'sale_team_warehouse', 'hr_passport_employee', 'product_unique_default_code', 'costing_method_settings', 'hr_blood_type', 'purchase_requisition_for_everybo
dy', 'purchase_requisition', 'l10n_pa_cities', 'stock_transfer_avoid_lot_repeated_split', 'stock_forecast', 'analytic', 'account_anglo_saxon', 'purchase_incoming_qty', 'hr
_loan', 'product_properties_by_category', 'hr_lastname', 'purchase_double_validation', 'hr_employee_perception', 'fiscal_printer', 'l10n_pa', 'hr_family', 'l10n_pa_hr_mari
tal_status', 'product_manufacturer', 'hr_employee_accessories', 'product_unique_serial', 'l10n_pa_vat', 'crm_claim_summary_report', 'base_vat', 'base_location', 'mrp', 'ac
count_asset', 'procurement_jit', 'vat_partitioned', 'hr_employee_dependant', 'product_lifecycle', 'uom_security', 'instance_introspection', 'auth_password_settings', 'hr_w
orking_shifts_switch'])

>>> len(yoytec_app_depends), len(real_yoytec_modules), len(set(yoytec_app_depends) - set(real_yoytec_modules))
(62, 29, 47)
```

**Comment by moylop260** [comment]
@osvalr 

> @moylop260 what about using the stable openerp_template database from runbot instead?

The main issue that we found re-using `openerp_template` database is when a module of template step change the `xml` with `noupdate="1"` and this change is important for a test.

This should works if we have all cases of update a module.
- When a `xml noupdate="1"` is changed in the diff...
- When a csv change xml_id
- When a new default is added or changed.
- When a new `create super` is inherited.
- and so on...

We have the risk of have a false red or a false green.

**Comment by moylop260** [comment]
@zaoral 

> I think maybe a 3 database approach could be useful.

This was my first way...
But I found that If I install the `-i module_x,module_y,module_z` and after I execute `-u module_x --test-enable` show errors because maybe the `module_z` change a demo data or add a new python logic that broke the tests of `module_x`

Then we will have even a red in many cases.

**Comment by moylop260** [comment]
@yaniaular

> Currently, when the openep_test BD is duplicated from openerp_template bd, it will proceed to install 62 modules (all modules in yoytec_app_depends).

You approach is right!
Indeed, the current method works very similar to your idea.
But add the parameter: "TESTING_OTHER_PROJECTS" in this case we need to test `addons-vauxoo` too as part of `yoytec` modules, because `addons-vauxoo` don't have a creation of CI instance and tests.

**Comment by osvalr** [comment]
> The main issue that we found re-using openerp_template database is when a module of template step change the xml with noupdate="1" and this change is important for a test.

I don't get this case, give me some light here

---

Just for the record dude: It'll be using the last stable generated database in runbot that it will be the same that is built, or am I missing something?

**Comment by zaoral** [comment]
@moylop260 

> But I found that If I install the -i module_x,module_y,module_z and after I execute -u module_x --test-enable show errors because maybe the module_z change a demo data

Well I agree with you. I think that this is the current situation but it should be not. I think that any odoo workflow could be updated via -u module without returning data errors: Perhaps we should find what is happening with this modules to avoid this errors. Also, a module unit test should only depends on its own data so update the data of another module should not be a problem in a run test for the change module.

>  or add a new python logic that broke the tests of module_x

About this is a real trouble but I think this only happens when changing modules that are not from our customer repo (specific modules): This modules should be installed in openerp_template or openerp_base without pass for any test. You think this module should be tested in openerp_test database, or maybe we should add a new unit test in our customer modules that make the extra unit test for the generic module with yoytec conditions (this taking into account that if it is a generic module means that probability our customer module extend it to modify it or set a configuration for our customer).

**Comment by moylop260** [comment]
FYI We are researching about [PSQL-non-durability](http://www.postgresql.org/docs/current/static/non-durability.html)

**Comment by moylop260** [comment]
FYI this is a important matter: http://colinwren.is/patching-out-registries-in-odoo-tests.html and http://www.slideshare.net/lepistone/odoo-testing-on-steroids
