### ISSUE TITLE
sed: can't read /root/*/openerp/cli/server.py: No such file or directory

### ISSUE THREAD

**Issue by shepilov-vladislav** [Vauxoo/runbot-addons#80]
always I get this error (
![screenshot-runbot xpansa com 2016-06-23 16-27-19](https://cloud.githubusercontent.com/assets/15679834/16304780/06ecb712-3968-11e6-8166-0b0787d395d4.png)
[job_10_test_base.txt](https://github.com/Vauxoo/runbot-addons/files/330043/job_10_test_base.txt)
[job_20_test_all.txt](https://github.com/Vauxoo/runbot-addons/files/330045/job_20_test_all.txt)
[job_30_run.txt](https://github.com/Vauxoo/runbot-addons/files/330044/job_30_run.txt)

**Comment by moylop260** [comment]
In the folder `/root/build/odoo-generic/module_git_need_update` Are there valid modules/**openerp**.py?

**Comment by shepilov-vladislav** [comment]
![screenshot at 2016-06-23 18 40 51](https://cloud.githubusercontent.com/assets/15679834/16309648/92a2debe-397a-11e6-88f9-856f8e9b0368.png)

**Comment by shepilov-vladislav** [comment]
https://github.com/vauxoo-dev/runbot_branch_remote_name_grp_feature2

doesn't start build anyway

**Comment by moylop260** [comment]
Open https://git.xpansa.com/odoo-generic/module_need_git_update.git
And check that exists the structure
- /root/
  - module1/
    - `__openerp__.py`
    - `__init__.py`

This hypothesis is base on a common error of use:
- /root/
  - <s>module1/</s>
    - `__openerp__.py`
    - <s> `__init__.py`</s>

**Comment by shepilov-vladislav** [comment]
![screenshot-git xpansa com 2016-06-23 19-27-33](https://cloud.githubusercontent.com/assets/15679834/16311295/0c29837c-3981-11e6-83d6-12a2bff8f059.png)
![screenshot-git xpansa com 2016-06-23 19-26-31](https://cloud.githubusercontent.com/assets/15679834/16311271/ec7d17d2-3980-11e6-9d54-0332407e2908.png)

**Comment by moylop260** [comment]
The content of `modue_git_need_update` is
- `__openerp__.py`
- `__init__.py`

?

**Comment by shepilov-vladislav** [comment]
yep

**Comment by shepilov-vladislav** [comment]
[travis.txt](https://github.com/Vauxoo/runbot-addons/files/330409/travis.txt)

**Comment by moylop260** [comment]
`__openerp__.py` has `installable: False`?

**Comment by shepilov-vladislav** [comment]
`installable: True`

**Comment by shepilov-vladislav** [comment]
And I see another error on https://github.com/vauxoo-dev/runbot_branch_remote_name_grp_feature2

```
Creating instance:
/root/odoo-8.0/openerp-server -d openerp_template --log-level=info --stop-after-init --init web,base
[Errno 2] No such file or directory
```

**Comment by moylop260** [comment]
The real error here is:

``` bash
Working in /root/build/odoo-generic/module_git_need_update
Using repo odoo/odoo and addons path /root/build/odoo-generic/module_git_need_update,/root/odoo-8.0/addons
********WARNING!***********
*********Nothing to test- exiting early.************
```

A common issue is when the build project path don't have valid odoo modules `/root/build/odoo-generic/module_git_need_update` then don't found nothing to tests.

This is because we have a syntax error, or a missed `__init__.py` or a missed `__openerp__.py` or a `installable: False`

But I can't see your module to confirm/discard this hypothesis

You could run:
travisfile2dockerfile git@git.xpansa.com:odoo-generic/module_git_need_update.git 8.0
Run the script: 10-build.sh
And run the script: `20-run.sh --entrypoint=bash`
In the container run: `/entypoint.sh`
After that... check if you can use:
`~/odoo-8.0/odoo.py -d openerp_template -i modue_git_need_update`

**Comment by shepilov-vladislav** [comment]
```
root@fec71352ef32:~# ls
build  maintainer-quality-tools  tools
root@fec71352ef32:~# ~/odoo-8.0/odoo.py -d openerp_template -i modue_git_need_update
bash: /root/odoo-8.0/odoo.py: No such file or directory
```

on latest step

**Comment by shepilov-vladislav** [comment]
issue solved with this config https://github.com/vauxoo-dev/runbot_branch_remote_name_grp_feature2/blob/8.0/.travis.yml

GREAT THANK YOU!
