### ISSUE TITLE
[IMP] runbot_travis2docker: Use of `authorized_keys` from github.com/USER.keys

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/runbot-addons#81]
Github has implemented a way to get your keys with the following url
https://github.com/YOUR_USER.keys

runbot_travis2docker use a "-v" to add authorized keys to allow connect it by ssh to build instance.
If we re-use the github keys based on commit author maybe we can avoid maintain a `authorized_keys` file updated manually and just the technicall user that create the build could connect it

Thanks @ruiztulio by the info.

**Comment by moylop260** [comment]
@nhomar What do you think about?

**Comment by nhomar** [comment]
I am with you and tulio's decision
