### ISSUE TITLE
Runbot information not present in PR tests' widget 

### ISSUE THREAD

**Issue by mapuerta** [Vauxoo/runbot-addons#82]
At the github link widget is not shown Runbot
more details Vauxoo/odoo.com.mx#9
![faild](https://cloud.githubusercontent.com/assets/16363083/17153970/fd1e13da-534c-11e6-8b1f-b7579940cdd9.png)

**Comment by ebirbe** [comment]
Any idea of why this problem?

We cannot see the runbot builds in any PR and it makes hard to do the reviews.

/cc @moylop260 @dsabrinarg

**Comment by moylop260** [comment]
Could you check my last comment from: https://github.com/Vauxoo/mexico-page/issues/9
I don't have idea of why runbot don't support report github statuses with project named with dots `my.repo`

Maybe is a bug of the core of runbot

**Comment by moylop260** [comment]
https://github.com/Vauxoo/odoo-extra/pull/91
FYI this pr fix this issue

**Comment by moylop260** [comment]
FYI fix https://github.com/Vauxoo/odoo-extra/pull/91
