### ISSUE TITLE
404 Not Found response when using Try-me button 

### ISSUE THREAD

**Issue by osvalr** [Vauxoo/runbot-addons#88]
When using the try me button for runbot build I'm getting the following 404 Not Found response

> ![image](https://cloud.githubusercontent.com/assets/2961943/22868058/e7842890-f156-11e6-9954-aaf1389b6e5d.png)

the try-me button is set in README file like the following
```
[![Try me on Runbot](https://odoo-community.org/website/image/ir.attachment/5784_f2813bd/datas)](http://runbot.vauxoo.com/runbot/3/10.0)
```
it displays as usual:

[![Try me on Runbot](https://odoo-community.org/website/image/ir.attachment/5784_f2813bd/datas)](http://runbot.vauxoo.com/runbot/3/10.0)

I checked runbot configuration for the repository configured there and also compared with another existing there and it seems be that nothing is missing but different behavior

**Comment by moylop260** [comment]
Fixed and deployed on runbot.vauxoo.com, thanks!
